Fix breaking migration
This migration seemingly fixes a prior migration issue, but on a fresh
run, it's the one that breaks:

    > php artisan migrate

    Migrating: 2020_02_03_205615_oops

       Illuminate\Database\QueryException  : SQLSTATE[HY000]: General
       error: 1 Cannot add a NOT NULL column with default value NULL
       (SQL: alter table "lineups" add column "player_id" integer not null)